# RQ1: What Key Factors Lead to Late Deliveries, and How Can We Proactively Identify High-Risk Orders to Improve Customer Satisfaction?

## Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.decomposition import TruncatedSVD
from imblearn.over_sampling import SMOTE

from sklearn.metrics import classification_report, roc_auc_score

## Importing Dataset

In [2]:
data = pd.read_csv("../data/cleaned/cleaned_dataset.csv")

data.head()

,order_id,order_item_id,order_status,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,is_canceled,customer_id,customer_unique_id,customer_zip_code_prefix,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume,review_id,review_score,delivered_late,delivery_delay
0,e481f51cbdc54678b7cc49136f2d6af7,1.0,delivered,2017-10-02,2017-10-02,2017-10-18,False,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,1976.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,False,-8.0
1,53cdb2fc8bc7dce0b6741e2150273451,1.0,delivered,2018-07-24,2018-07-26,2018-08-13,False,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,47813,...,1.0,400.0,19.0,13.0,19.0,4693.0,8d5266042046a06655c8db133d120ba5,4.0,False,-6.0
2,47770eb9100c2d0c44946d9cf07ec65d,1.0,delivered,2018-08-08,2018-08-08,2018-09-04,False,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,420.0,24.0,19.0,21.0,9576.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,False,-18.0
3,949d5b44dbf5de918fe9c16f97b45f8a,1.0,delivered,2017-11-18,2017-11-18,2017-12-15,False,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,59296,...,3.0,450.0,30.0,10.0,20.0,6000.0,359d03e676b3c069f62cadba8dd3f6e8,5.0,False,-13.0
4,ad21c59c0840e6cb83a9ceb5573f8159,1.0,delivered,2018-02-13,2018-02-13,2018-02-26,False,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,4.0,250.0,51.0,15.0,15.0,11475.0,e50934924e227544ba8246aeb3770dd4,5.0,False,-10.0

In [3]:
data.columns

Index(['order_id', 'order_item_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_estimated_delivery_date', 'is_canceled',
       'customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'customer_lat', 'customer_lng',
       'order_delivered_customer_date', 'is_first_time_buyer', 'seller_id',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'seller_lat',
       'seller_lng', 'shipping_limit_date', 'order_delivered_carrier_date',
       'handoff_delay', 'distance_km', 'product_id',
       'product_category_name_english', 'price', 'freight_value',
       'product_name_length', 'product_description_length',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm', 'product_volume', 'review_id',
       'review_score', 'delivered_late', 'delivery_delay'],
      dtype='object')

## Pre-Processing

### Removing Unnecessary Columns

In [4]:
data.drop(columns=['order_id', 
                   'order_item_id', 
                   'order_status', 
                   'order_purchase_timestamp', 
                   'order_approved_at',
                   'order_estimated_delivery_date',
                   'is_canceled',
                   'customer_id',
                   'customer_unique_id',
                   'customer_zip_code_prefix',
                   'customer_state',
                   'customer_lat',
                   'customer_lng',
                   'order_delivered_customer_date',
                   'is_first_time_buyer',
                   'seller_zip_code_prefix',
                   'seller_state',
                   'seller_lat',
                   'seller_lng',
                   'shipping_limit_date',
                   'order_delivered_carrier_date',
                   'price',
                   'freight_value',
                   'product_name_length',
                   'product_description_length',
                   'product_photos_qty',
                   'review_id',
                   'review_score',
                   'product_id',
                   'delivery_delay'], inplace=True)

display(data.head())

display(data.shape)

,customer_city,seller_id,seller_city,handoff_delay,distance_km,product_category_name_english,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_volume,delivered_late
0,sao paulo,3504c0cb71d7fa48d967e0e4c94d59d9,maua,-2.0,18.576110,housewares,500.0,19.0,8.0,13.0,1976.0,False
1,barreiras,289cdb325fb7e7f891c38608bf9e0962,belo horizonte,-4.0,851.495069,perfumery,400.0,19.0,13.0,19.0,4693.0,False
2,vianopolis,4869f7a5dfa277a7dca6462dcf3b52b2,guariba,-5.0,514.410666,auto,420.0,24.0,19.0,21.0,9576.0,False
3,sao goncalo do amarante,66922902710d126a0e7d26b0e3805106,belo horizonte,-1.0,1822.226336,pet_shop,450.0,30.0,10.0,20.0,6000.0,False
4,santo andre,2c9e548be18521d1c43cde1c582c6de8,mogi das cruzes,-5.0,29.676625,stationery,250.0,51.0,15.0,15.0,11475.0,False

(111717, 12)

### Removing NA Rows

In [5]:
data = data.dropna()

display(data.shape)

(108983, 12)

### Variable Selection

In [6]:
X = data.drop(columns=['delivered_late'])
y = data['delivered_late']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

### Encoding Variables

In [7]:
categorical_features = ['customer_city',
                        'seller_city', 
                        'seller_id',
                        'product_category_name_english']

numerical_features = ['handoff_delay', 'distance_km', 'product_weight_g',
                      'product_length_cm', 'product_height_cm',
                      'product_width_cm', 'product_volume']

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=True), categorical_features),
    ('num', StandardScaler(), numerical_features)
])

# Transform
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

### Getting Feature Names

In [8]:
if hasattr(X_train_encoded, "toarray"):
    X_train_encoded = X_train_encoded.toarray()
    X_test_encoded = X_test_encoded.toarray()

# Get column names
cat_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
all_feature_names = list(cat_feature_names) + numerical_features

# Convert to DataFrames
X_train_df = pd.DataFrame(X_train_encoded, columns=all_feature_names)
X_test_df = pd.DataFrame(X_test_encoded, columns=all_feature_names)

### Applying SMOTE

In [9]:
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_df, y_train)

X_train_resampled.shape, y_train_resampled.shape, X_test_df.shape, y_test.shape, all_feature_names

((163140, 7211),
 (163140,),
 (21797, 7211),
 (21797,),
 ['customer_city_abadia dos dourados',
  'customer_city_abadiania',
  'customer_city_abaete',
  'customer_city_abaetetuba',
  'customer_city_abaiara',
  'customer_city_abaira',
  'customer_city_abare',
  'customer_city_abatia',
  'customer_city_abelardo luz',
  'customer_city_abrantes',
  'customer_city_abre campo',
  'customer_city_abreu e lima',
  'customer_city_acaiaca',
  'customer_city_acailandia',
  'customer_city_acajutiba',
  'customer_city_acarau',
  'customer_city_acari',
  'customer_city_acegua',
  'customer_city_acopiara',
  'customer_city_acreuna',
  'customer_city_acu',
  'customer_city_acucena',
  'customer_city_adamantina',
  'customer_city_adhemar de barros',
  'customer_city_adolfo',
  'customer_city_adrianopolis',
  'customer_city_afogados da ingazeira',
  'customer_city_afonso claudio',
  'customer_city_afranio',
  'customer_city_agisse',
  'customer_city_agrolandia',
  'customer_city_agronomica',
  'customer_city_agua boa',
  'customer_city_agua branca',
  'customer_city_agua clara',
  'customer_city_agua comprida',
  'customer_city_agua doce',
  'customer_city_agua doce do norte',
  'customer_city_agua fria de goias',
  'customer_city_agua santa',
  'customer_city_aguai',
  'customer_city_aguas belas',
  'customer_city_aguas claras',
  'customer_city_aguas da prata',
  'customer_city_aguas de lindoia',
  'customer_city_aguas de santa barbara',
  'customer_city_aguas de sao pedro',
  'customer_city_aguas formosas',
  'customer_city_aguas frias',
  'customer_city_aguas lindas de goias',
  'customer_city_aguas mornas',
  'customer_city_aguas vermelhas',
  'customer_city_agudos',
  'customer_city_aguia branca',
  'customer_city_aimores',
  'customer_city_aiuaba',
  'customer_city_aiuruoca',
  'customer_city_ajapi',
  'customer_city_ajuricaba',
  'customer_city_alagoa nova',
  'customer_city_alagoinha',
  'customer_city_alagoinhas',
  'customer_city_alambari',
  'customer_city_alcantara',
  'customer_city_alcinopolis',
  'customer_city_alcobaca',
  'customer_city_alegre',
  'customer_city_alegrete',
  'customer_city_alegrete do piaui',
  'customer_city_alegria',
  'customer_city_alem paraiba',
  'customer_city_alexandra',
  'customer_city_alexandria',
  'customer_city_alexandrita',
  'customer_city_alexania',
  'customer_city_alfenas',
  'customer_city_alfredo chaves',
  'customer_city_alfredo marcondes',
  'customer_city_alfredo vasconcelos',
  'customer_city_alfredo wagner',
  'customer_city_alhandra',
  'customer_city_alianca',
  'customer_city_alianca do tocantins',
  'customer_city_almas',
  'customer_city_almenara',
  'customer_city_almirante tamandare',
  'customer_city_almirante tamandare do sul',
  'customer_city_alpercata',
  'customer_city_alpestre',
  'customer_city_alpinopolis',
  'customer_city_alta floresta',
  "customer_city_alta floresta d'oeste",
  'customer_city_altamira',
  'customer_city_altamira do parana',
  'customer_city_altaneira',
  'customer_city_alterosa',
  'customer_city_altinho',
  'customer_city_altinopolis',
  'customer_city_alto alegre',
  'customer_city_alto alegre do iguacu',
  'customer_city_alto alegre do maranhao',
  'customer_city_alto araguaia',
  'customer_city_alto boa vista',
  'customer_city_alto caparao',
  'customer_city_alto do rodrigues',
  'customer_city_alto garcas',
  'customer_city_alto jequitiba',
  'customer_city_alto paraiso',
  'customer_city_alto paraiso de goias',
  'customer_city_alto parana',
  'customer_city_alto parnaiba',
  'customer_city_alto piquiri',
  'customer_city_alto rio doce',
  'customer_city_alto rio novo',
  'customer_city_alto santo',
  'customer_city_alto taquari',
  'customer_city_altonia',
  'customer_city_altos',
  'customer_city_aluminio',
  'customer_city_alvarenga',
  'customer_city_alvares florence',
  'customer_city_alvares machado',
  'customer_city_alvaro de carvalho',
  'customer_city_alvinopolis',
  'customer_city_alvorada',
  "customer_city_alvorada d'oeste",
  'customer_city_alvorada do gurgueia',
  'customer_city_alvorada do norte',
  'customer_city_amambai',
  'customer_city_amanari',
  'customer_city_amapa do maranhao',
  'customer_city_amapora',
  'customer_city_amaraji',
  'customer_city_amargosa',
  'customer_city_amelia rodrigues',
  'customer_city_america dourada',
  'customer_city_americana',
  'customer_city_americano do brasil',
  'customer_city_americo brasiliense',
  'customer_city_americo de campos',
  'customer_city_ametista do sul',
  'customer_city_amontada',
  'customer_city_amparo',
  'customer_city_amparo da serra',
  'customer_city_ampere',
  'customer_city_anadia',
  'customer_city_anage',
  'customer_city_analandia',
  'customer_city_ananas',
  'customer_city_ananindeua',
  'customer_city_anapolis',
  'customer_city_anastacio',
  'customer_city_anaurilandia',
  'customer_city_anchieta',
  'customer_city_andarai',
  'customer_city_andira',
  'customer_city_andorinha',
  'customer_city_andradas',
  'customer_city_andradina',
  'customer_city_andrelandia',
  'customer_city_andrequice',
  'customer_city_angatuba',
  'customer_city_angelica',
  'customer_city_angelina',
  'customer_city_angicos',
  'customer_city_angra dos reis',
  'customer_city_anguera',
  'customer_city_angulo',
  'customer_city_angustura',
  'customer_city_anhandui',
  'customer_city_anhembi',
  'customer_city_anhumas',
  'customer_city_anicuns',
  'customer_city_anita garibaldi',
  'customer_city_anitapolis',
  'customer_city_anta',
  'customer_city_anta gorda',
  'customer_city_antonina',
  'customer_city_antonina do norte',
  'customer_city_antonio cardoso',
  'customer_city_antonio carlos',
  'customer_city_antonio goncalves',
  'customer_city_antonio martins',
  'customer_city_antonio pereira',
  'customer_city_antonio prado',
  'customer_city_antonio prado de minas',
  'customer_city_aparecida',
  "customer_city_aparecida d'oeste",
  'customer_city_aparecida de goiania',
  'customer_city_aparecida de monte alto',
  'customer_city_aparecida de sao manuel',
  'customer_city_aparecida do rio negro',
  'customer_city_aparecida do taboado',
  'customer_city_aperibe',
  'customer_city_apiaca',
  'customer_city_apiacas',
  'customer_city_apiai',
  'customer_city_apiuna',
  'customer_city_apodi',
  'customer_city_apora',
  'customer_city_apore',
  'customer_city_apuarema',
  'customer_city_apucarana',
  'customer_city_apuiares',
  'customer_city_aquidauana',
  'customer_city_aquiraz',
  'customer_city_aracaju',
  'customer_city_aracariguama',
  'customer_city_aracati',
  'customer_city_aracatuba',
  'customer_city_arace',
  'customer_city_araci',
  'customer_city_aracitaba',
  'customer_city_aracoiaba',
  'customer_city_aracoiaba da serra',
  'customer_city_aracruz',
  'customer_city_aracuai',
  'customer_city_aragarcas',
  'customer_city_araguacu',
  'customer_city_araguaia',
  'customer_city_araguaina',
  'customer_city_araguapaz',
  'customer_city_araguari',
  'customer_city_araguatins',
  'customer_city_aramari',
  'customer_city_arame',
  'customer_city_arandu',
  'customer_city_arantina',
  'customer_city_arapei',
  'customer_city_arapiraca',
  'customer_city_arapoema',
  'customer_city_araponga',
  'customer_city_arapongas',
  'customer_city_arapora',
  'customer_city_arapoti',
  'customer_city_arapua',
  'customer_city_araputanga',
  'customer_city_araquari',
  'customer_city_arara',
  'customer_city_ararangua',
  'customer_city_araraquara',
  'customer_city_araras',
  'customer_city_arari',
  'customer_city_ararica',
  'customer_city_araripe',
  'customer_city_araripina',
  'customer_city_araruama',
  'customer_city_araruna',
  'customer_city_arataca',
  'customer_city_aratuba',
  'customer_city_araucaria',
  'customer_city_araujos',
  'customer_city_araxa',
  'customer_city_arceburgo',
  'customer_city_arcos',
  'customer_city_arcoverde',
  'customer_city_areado',
  'customer_city_areal',
  'customer_city_arealva',
  'customer_city_areia',
  'customer_city_areia branca',
  'customer_city_areia branca dos assis',
  'customer_city_areial',
  'customer_city_areias',
  'customer_city_areiopolis',
  'customer_city_arembepe',
  'customer_city_arenapolis',
  'customer_city_arinos',
  'customer_city_aripuana',
  'customer_city_ariquemes',
  'customer_city_ariranha',
  'customer_city_armacao dos buzios',
  'customer_city_arneiroz',
  'customer_city_aroeiras',
  'customer_city_arraial d ajuda',
  "customer_city_arraial d'ajuda",
  'customer_city_arraial do cabo',
  'customer_city_arraias',
  'customer_city_arroio do meio',
  'customer_city_arroio do sal',
  'customer_city_arroio do tigre',
  'customer_city_arroio dos ratos',
  'customer_city_arroio grande',
  'customer_city_arrozal',
  'customer_city_artur nogueira',
  'customer_city_aruana',
  'customer_city_aruja',
  'customer_city_arvoredo',
  'customer_city_arvorezinha',
  'customer_city_ascurra',
  'customer_city_assai',
  'customer_city_assare',
  'customer_city_assis',
  'customer_city_assis chateaubriand',
  'customer_city_assuncao',
  'customer_city_astolfo dutra',
  'customer_city_astorga',
  'customer_city_atalaia',
  'customer_city_atalanta',
  'customer_city_ataleia',
  'customer_city_atibaia',
  'customer_city_atilio vivacqua',
  'customer_city_augustinopolis',
  'customer_city_augusto correa',
  'customer_city_augusto pestana',
  'customer_city_aurea',
  'customer_city_auriflama',
  'customer_city_aurilandia',
  'customer_city_aurora',
  'customer_city_aurora do para',
  'customer_city_avanhandava',
  'customer_city_avare',
  'customer_city_avelar',
  'customer_city_avelino lopes',
  'customer_city_azurita',
  'customer_city_bacabal',
  'customer_city_bacaxa',
  'customer_city_bacuri',
  'customer_city_bady bassitt',
  'customer_city_baependi',
  'customer_city_bage',
  'customer_city_baguari',
  'customer_city_baianopolis',
  'customer_city_baixa grande',
  'customer_city_baixa grande do ribeiro',
  'customer_city_baixo guandu',
  'customer_city_balbinos',
  'customer_city_baldim',
  'customer_city_balneario arroio do silva',
  'customer_city_balneario barra do sul',
  'customer_city_balneario camboriu',
  'customer_city_balneario gaivota',
  'customer_city_balneario picarras',
  'customer_city_balneario pinhal',
  'customer_city_balneario rincao',
  'customer_city_balsamo',
  'customer_city_balsas',
  'customer_city_bambui',
  'customer_city_banabuiu',
  'customer_city_bananal',
  'customer_city_bananeiras',
  'customer_city_bandeira',
  'customer_city_bandeira do sul',
  'customer_city_bandeirantes',
  'customer_city_bandeirantes do tocantins',
  'customer_city_barao',
  'customer_city_barao de cocais',
  'customer_city_barao de cotegipe',
  'customer_city_barao de juparana',
  'customer_city_barao do triunfo',
  'customer_city_barauna',
  'customer_city_barbacena',
  'customer_city_barbalha',
  'customer_city_barbosa ferraz',
  'customer_city_barcarena',
  'customer_city_bariri',
  'customer_city_barra',
  'customer_city_barra bonita',
  'customer_city_barra da estiva',
  'customer_city_barra de guabiraba',
  'customer_city_barra de santa rosa',
  'customer_city_barra de santo antonio',
  'customer_city_barra de sao francisco',
  'customer_city_barra de sao joao',
  'customer_city_barra de sao miguel',
  'customer_city_barra do bugres',
  'customer_city_barra do corda',
  'customer_city_barra do garcas',
  'customer_city_barra do mendes',
  'customer_city_barra do pirai',
  'customer_city_barra do ribeiro',
  'customer_city_barra do rio azul',
  'customer_city_barra do tarrachil',
  'customer_city_barra do turvo',
  'customer_city_barra dos coqueiros',
  'customer_city_barra mansa',
  'customer_city_barra velha',
  'customer_city_barracao',
  'customer_city_barras',
  'customer_city_barreiras',
  'customer_city_barreirinhas',
  'customer_city_barreiros',
  'customer_city_barretos',
  'customer_city_barrinha',
  'customer_city_barro',
  'customer_city_barro alto',
  'customer_city_barrocas',
  'customer_city_barrolandia',
  'customer_city_barros cassal',
  'customer_city_barroso',
  'customer_city_barueri',
  'customer_city_bastos',
  'customer_city_bataguassu',
  'customer_city_bataipora',
  'customer_city_batalha',
  'customer_city_batatais',
  'customer_city_bataypora',
  'customer_city_baturite',
  'customer_city_bauru',
  'customer_city_bayeux',
  'customer_city_bebedouro',
  'customer_city_beberibe',
  'customer_city_bela cruz',
  'customer_city_bela vista',
  'customer_city_bela vista de goias',
  'customer_city_bela vista de minas',
  'customer_city_bela vista do maranhao',
  'customer_city_bela vista do paraiso',
  'customer_city_belem',
  'customer_city_belem do sao francisco',
  'customer_city_belford roxo',
  'customer_city_belmonte',
  'customer_city_belo campo',
  'customer_city_belo horizonte',
  'customer_city_belo jardim',
  'customer_city_belo oriente',
  'customer_city_belo vale',
  'customer_city_benedito leite',
  'customer_city_benedito novo',
  'customer_city_benevides',
  'customer_city_bento de abreu',
  'customer_city_bento goncalves',
  'customer_city_berizal',
  'customer_city_bernardino de campos',
  'customer_city_bertioga',
  'customer_city_betim',
  'customer_city_bezerros',
  'customer_city_bias fortes',
  'customer_city_bicas',
  'customer_city_biguacu',
  'customer_city_bilac',
  'customer_city_birigui',
  'customer_city_biritiba-mirim',
  'customer_city_bituruna',
  'customer_city_blumenau',
  'customer_city_boa esperanca',
  'customer_city_boa esperanca do iguacu',
  'customer_city_boa esperanca do sul',
  'customer_city_boa viagem',
  'customer_city_boa vista',
  'customer_city_boa vista da aparecida',
  'customer_city_boa vista do burica',
  'customer_city_boa vista do cadeado',
  'customer_city_boa vista do gurupi',
  'customer_city_boa vista do sul',
  'customer_city_boca da mata',
  'customer_city_bocaina',
  'customer_city_bocaiuva',
  'customer_city_bocaiuva do sul',
  'customer_city_bodo',
  'customer_city_bodoco',
  'customer_city_bodoquena',
  'customer_city_bofete',
  'customer_city_boituva',
  'customer_city_bom conselho',
  'customer_city_bom despacho',
  'customer_city_bom jardim',
  'customer_city_bom jardim de goias',
  'customer_city_bom jardim de minas',
  'customer_city_bom jesus',
  'customer_city_bom jesus da lapa',
  'customer_city_bom jesus da penha',
  'customer_city_bom jesus da serra',
  'customer_city_bom jesus das selvas',
  'customer_city_bom jesus do araguaia',
  'customer_city_bom jesus do galho',
  'customer_city_bom jesus do itabapoana',
  'customer_city_bom jesus do norte',
  'customer_city_bom jesus do tocantins',
  'customer_city_bom jesus dos perdoes',
  'customer_city_bom principio',
  'customer_city_bom repouso',
  'customer_city_bom retiro',
  'customer_city_bom sucesso',
  'customer_city_bombinhas',
  'customer_city_bonfim',
  'customer_city_bonfim paulista',
  'customer_city_bonfinopolis',
  'customer_city_boninal',
  'customer_city_bonito',
  'customer_city_bonito de minas',
  'customer_city_bonito de santa fe',
  'customer_city_boqueirao do leao',
  'customer_city_boquim',
  'customer_city_boquira',
  'customer_city_boraceia',
  'customer_city_borborema',
  'customer_city_borda da mata',
  'customer_city_borrazopolis',
  'customer_city_bossoroca',
  'customer_city_botelhos',
  'customer_city_botucatu',
  'customer_city_botupora',
  'customer_city_botuvera',
  'customer_city_braco do norte',
  'customer_city_braco do rio',
  'customer_city_braganca',
  'customer_city_braganca paulista',
  'customer_city_bras pires',
  'customer_city_brasil novo',
  'customer_city_brasilandia',
  'customer_city_brasilandia de minas',
  'customer_city_brasileia',
  'customer_city_brasilia',
  'customer_city_brasilia de minas',
  'customer_city_brasopolis',
  'customer_city_brauna',
  'customer_city_braunas',
  'customer_city_brazabrantes',
  'customer_city_brazopolis',
  'customer_city_brejo',
  'customer_city_brejo da madre de deus',
  'customer_city_brejo do cruz',
  'customer_city_brejo dos santos',
  'customer_city_brejo santo',
  'customer_city_brejoes',
  'customer_city_breu branco',
  'customer_city_breves',
  'customer_city_britania',
  'customer_city_brodowski',
  'customer_city_brotas',
  'customer_city_brotas de macaubas',
  'customer_city_brumadinho',
  'customer_city_brumado',
  'customer_city_brusque',
  'customer_city_bueno brandao',
  'customer_city_buenopolis',
  'customer_city_buenos aires',
  'customer_city_buerarema',
  'customer_city_bugre',
  'customer_city_buique',
  'customer_city_buri',
  'customer_city_buritama',
  'customer_city_buriti',
  'customer_city_buriti do tocantins',
  'customer_city_buriti dos lopes',
  'customer_city_buriticupu',
  'customer_city_buritirama',
  'customer_city_buritis',
  'customer_city_buritizal',
  'customer_city_buritizeiro',
  'customer_city_butia',
  'customer_city_caarapo',
  'customer_city_cabeceira grande',
  'customer_city_cabeceiras',
  'customer_city_cabedelo',
  'customer_city_cabixi',
  'customer_city_cabo de santo agostinho',
  'customer_city_cabo frio',
  'customer_city_cabo verde',
  'customer_city_cabralia paulista',
  'customer_city_cabreuva',
  'customer_city_cabrobo',
  'customer_city_cacador',
  'customer_city_cacapava',
  'customer_city_cacapava do sul',
  'customer_city_cacaulandia',
  'customer_city_cacequi',
  'customer_city_caceres',
  'customer_city_cachoeira',
  'customer_city_cachoeira alta',
  'customer_city_cachoeira da prata',
  'customer_city_cachoeira de minas',
  'customer_city_cachoeira de pajeu',
  'customer_city_cachoeira do brumado',
  'customer_city_cachoeira do campo',
  'customer_city_cachoeira do sul',
  'customer_city_cachoeira dourada',
  'customer_city_cachoeira paulista',
  'customer_city_cachoeiras de macacu',
  'customer_city_cachoeirinha',
  'customer_city_cachoeiro de itapemirim',
  'customer_city_cacoal',
  'customer_city_caconde',
  'customer_city_cacu',
  'customer_city_cacule',
  'customer_city_caem',
  'customer_city_caetanopolis',
  'customer_city_caete',
  'customer_city_caetes',
  'customer_city_caetite',
  'customer_city_cafeara',
  'customer_city_cafelandia',
  'customer_city_caiana',
  'customer_city_caiaponia',
  'customer_city_caibate',
  'customer_city_caibi',
  'customer_city_caicara do norte',
  'customer_city_caico',
  'customer_city_caieiras',
  'customer_city_cairu',
  'customer_city_caiua',
  'customer_city_cajamar',
  'customer_city_cajapio',
  'customer_city_cajari',
  'customer_city_cajati',
  'customer_city_cajazeiras',
  'customer_city_cajobi',
  'customer_city_cajueiro',
  'customer_city_cajuri',
  'customer_city_cajuru',
  'customer_city_calcado',
  'customer_city_caldas',
  'customer_city_caldas brandao',
  'customer_city_caldas novas',
  'customer_city_caldeirao grande',
  'customer_city_caldeirao grande do piaui',
  'customer_city_california',
  'customer_city_california da barra',
  'customer_city_calmon',
  'customer_city_camacan',
  'customer_city_camacari',
  'customer_city_camacho',
  'customer_city_camamu',
  'customer_city_camanducaia',
  'customer_city_camapua',
  'customer_city_camaqua',
  'customer_city_camaragibe',
  'customer_city_cambara',
  'customer_city_cambara do sul',
  'customer_city_cambe',
  'customer_city_cambiasca',
  'customer_city_cambira',
  'customer_city_camboriu',
  'customer_city_cambuci',
  'customer_city_cambui',
  'customer_city_cambuquira',
  'customer_city_cameta',
  'customer_city_camocim',
  'customer_city_camocim de sao felix',
  'customer_city_campanario',
  'customer_city_campanha',
  'customer_city_campestre',
  'customer_city_campestre da serra',
  'customer_city_campestre do maranhao',
  'customer_city_campina da lagoa',
  'customer_city_campina das missoes',
  'customer_city_campina do monte alegre',
  'customer_city_campina grande',
  'customer_city_campina grande do sul',
  'customer_city_campina verde',
  'customer_city_campinacu',
  'customer_city_campinapolis',
  'customer_city_campinas',
  'customer_city_campinas do sul',
  'customer_city_campinorte',